# netlify.toml

# Function schedule for Netlify

# BEFORE: This runs the "sync-with-google-sheets" function every 15 minutes.
# [functions."sync-with-google-sheets"]
#   schedule = "*/15 * * * *"

# AFTER (RECOMMENDED): This runs the function daily at 6:00 AM UTC.
[functions."sync-with-google-sheets"]
  schedule = "0 6 * * *"
